### PR TITLE
fixed

### LINKED ISSUE #6: Early Return
https://github.com/Wibur/pxmartCrawler/blob/304ca12eba393ada68c7569e293152098d9a9f55/crawler/crawler.go#L34-L36

The early returns are required in every err handling.

### LINKED ISSUE #7: Response Error JSON
https://github.com/Wibur/pxmartCrawler/blob/304ca12eba393ada68c7569e293152098d9a9f55/service/recipes.go#L20

[gin.H](https://pkg.go.dev/github.com/gin-gonic/gin#readme-quick-start) is pretty useful for c.JSON responses, and better than pure string responses.

### PR DESCRIPTION
**Pull request by Wibur**
resolved #6

### CODE REVIEW

**Comment by Wibur** [comment]
resolved #6 #7

**Comment by Wibur** [comment]
resolved #6 #7

**Review by shadow3x3x3 — CHANGES_REQUESTED** [review]
missing returns

**Comment by Wibur** [comment]
branch so old

**Comment by shadow3x3x3** [comment]
@Wibur 
you could merge the latest branch into this one and fix this issue

**Pull request closed without merging**
